### ISSUE TITLE
[BUG] Docs search seems to be broken(?)

### ISSUE THREAD

**Issue by darcyclarke** [vltpkg/vltpkg#280]

**Comment by ejkorol** [comment]
@lukekarrys Looking through the preview deployments, it seems the search broke after #276 . Search seems to work locally when running `preview` but not in prod. Looks like the issue is caused by a missing script (pagefind.js) at the specified URL. Any ideas what this could be? <img width="742" alt="Image" src="https://github.com/user-attachments/assets/cb916ef1-50d6-43fb-9e44-c02951bffbb8" />
